# Generated by Django 5.0.2 on 2024-02-19 07:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('meeting_time', models.DateTimeField(default=datetime.datetime.now)),
                ('users', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'ordering': ['-meeting_time'],
                'indexes': [models.Index(fields=['meeting_time'], name='meeting_time_index')],
            },
        ),
    ]
